### ISSUE TITLE
V 3.0 beta Group's Files link broken

### ISSUE THREAD

**Issue by michelesbw** [ColdTrick/file_tools#65]
Hello,
with Elgg 2.2.3 when using sidebar's group files link it reloads groups main page, no files are shown
Ie SITE/file/group/567867/all 
Plugin disabled all files are there.
Cheers

**Comment by michelesbw** [comment]
It happened with master branch

**Comment by juho-jaakkola** [comment]
The link is not broken, but for some reason the `www.example.com/file/group/123/all` page makes a redirect instead of listing the files.

**Comment by jeabakker** [comment]
i\ll have a look later today

**Comment by jeabakker** [comment]
problem was a wrong check on page_owner
