### ISSUE TITLE
No files in the list

### ISSUE THREAD

**Issue by annivzinal** [ColdTrick/file_tools#66]
Hello,

I experienced a bug. With this plugin actived, I cannot see the list of files...

I have only the loader which turns, turns....and turn again... and nothing appears...

I am using elgg 2.1 and just change the release in the manifest file...

thanks

![capture](https://cloud.githubusercontent.com/assets/19345275/22254424/da3a6af2-e254-11e6-95ab-bb54a0019cc1.PNG)

**Comment by jdalsem** [comment]
I think there is a reason why in the manifest the plugin states it needs Elgg 2.2. You could download a previous version that does not require 2.2.

**Comment by annivzinal** [comment]
Which version should I download. With the version requires 1.9 there is bugs with widget manager... Is there a version which works with 2.1?

**Comment by jdalsem** [comment]
There is no version specifically tested/developed for Elgg 2.1. Best for you is to update to Elgg 2.2 (or 2.3).
