### ISSUE TITLE
Actions shouldn't set access_id to ACCESS_DEFAULT 

### ISSUE THREAD

**Issue by brettp** [ColdTrick/file_tools#67]
In actions (at least folder/edit), the default value for access_id is ACCESS_DEFAULT. There is no processing to reassign the real default access value for the user / site. If ACCESS_DEFAULT is used to save an entity, it causes `ElggEntity->save()` to throw an error.

**Comment by jdalsem** [comment]
this should be changed to get_default_access probably

**Comment by jeabakker** [comment]
only in the save action was this a potential problem. In the forms setting `$access_id` to `ACCESS_DEFAULT` was done to make sure `get_default_access()` was called.
