### ISSUE TITLE
There was an error while removing some folders

### ISSUE THREAD

**Issue by insideth** [ColdTrick/file_tools#69]
Folders can´t be deleted. 
ver. 3.0.0-rc.3
Elgg ver. 2.2

**Comment by jeabakker** [comment]
In order to help with this issue i need some more information.

- where was the folder located (user or group)
- who is trying to delete the folder (user, group owner, group member)
- did the error come from the folder being removed or from one of the child folders

**Comment by insideth** [comment]
Doing more tests I see problem only happens if you check (select) the folder/folders and you click on Delete selected bottom-left link. The same happens from user / group folders.

If you delete the folder from its own delete link it works.

**Comment by insideth** [comment]
I´ve upgraded to elgg 2.3 and problem dissapeared. I close the issue.
