### ISSUE TITLE
PHP Fatal error:  Call to a member function isValid() on null

### ISSUE THREAD

**Issue by dragonjon** [ColdTrick/file_tools#71]
Hi guys, when i upload file and save the upload the description is in html code
(this problem is only with files) and when I edit the file and correct the text of the description in the server it show this error:

PHP Fatal error:  Call to a member function isValid() on null in /public_html/mod/file_tools/actions/file/upload.php on line 38, referer: http://my site/file/edit/5398
If I refresh the browser show in the site this error "form is missing __token or __ts fields"

All time work all perfect, but today is the error
Thanks for the work

**Comment by jeabakker** [comment]
Which version of File Tools are you using? 

I can't see that we override the file upload action (from your error `mod/file_tools/actions/file/upload.php`)

**Comment by dragonjon** [comment]
The version I see in plugins puts 3.0 but I think this version is not possible. The version of Elgg is 2.1
I have compared the files of the plugin that I have installed with all the versions that you have in the repository and the one that seems more is the 2.0 but I lack folders and the files have differences. Something very strange.
I tried to upload version 2 that is the one that would suit me better, but all folders and files disappeared, if I restore my copy of the plugin appear again.
Everything worked well until yesterday without modifying anything in the system. I also can not edit any file without modifying anything, it gives me the same error.
I can send you the folder of the compressed plugin to see if you can guide me what happened.

**Comment by jeabakker** [comment]
> I can send you the folder of the compressed plugin to see if you can guide me what happened.

attach it to this issue, please

**Comment by dragonjon** [comment]
[file_tools.zip](https://github.com/ColdTrick/file_tools/files/1303228/file_tools.zip)

**Comment by jeabakker** [comment]
I think you're using a modified (not by ColdTrick) version of the plugin, I see lots of files that never existed in our version.

For a long time we didn't touch this plugin, so maybe somebody else made some modifications. We started working on it again in November 2016 for a client and since then it requires Elgg 2.2. I don't think any of our versions prior to 3.0 worked on Elgg 2.0+. And version 2.0 was made for Elgg 1.9.

I'm afraid i can't help you :(

**Comment by dragonjon** [comment]
Thank you for bothering to look at it, I will find out where that version came out, which will surely be what you tell me.
Thank you from a fan of your plugins.

**Comment by dragonjon** [comment]
Hello, from here came that version that will send you if it serves you in the future for other users who ask for help.
https://github.com/brettp/file_tools/tree/2.1.x
regards
