### ISSUE TITLE
504 Gatewat timeout 

### ISSUE THREAD

**Issue by Billaboong** [ColdTrick/file_tools#72]
I am getting the above error when uploading a file on only a particular group yet the other groups it is uploading fine.
When I reload the page the file is uploaded but not on the folder I had selected.
Please assist.

**Comment by jeabakker** [comment]
- what is the file size
- the same file in a different group gives the same error?
- an other (small) file in the 'problem' group works?
- does the 'problem' group have a large folder structure

PS:
- file_tools version
- elgg version

**Comment by Billaboong** [comment]
- file size: 1.6MB
- The same file in a different group uploads successfully.
- No, on the 'problem' group even a smaller file does not work.
- The 'problem' group does not have a large folder structure - It has only two folders

file_tools version : 1.1.2
elg versions : 1.8

**Comment by jeabakker** [comment]
We no longer support Elgg 1.8 (Elgg also doesn't support it anymore http://learn.elgg.org/en/stable/appendix/support.html). Please upgrade to a more recent version (eg. Elgg 2.3.x)

If you still have this issue after updating to a more recent version of Elgg (eg. 2.3.x) we can look into this again.

**Comment by Billaboong** [comment]
@jeabakker Thank you for taking your time and following up on the issue.

Lets look at other alternatives to this.
