### ISSUE TITLE
Fatal Error!  

### ISSUE THREAD

**Issue by XKolawole** [ColdTrick/file_tools#81]
File tool settings is not working in elgg 3.2. 
![Capture](https://user-images.githubusercontent.com/43893813/70167752-b3db0600-16c7-11ea-8ed8-b42493620caf.PNG)

**Comment by jdalsem** [comment]
Do you use Elgg 3.2.1 or 3.2.0... there is a fix in core that is required for this plugin

**Comment by XKolawole** [comment]
I use Elgg 3.2.0

Thank you for the reply

**Comment by jdalsem** [comment]
if you upgrade to Elgg 3.2.1 your problem is solved
