### ISSUE TITLE
Fix missing OrderByClause fatal error in group files list

### ISSUE THREAD

**Issue by Facyla** [ColdTrick/file_tools#85]
**Elgg version**
Elgg 3.3.24

**Plugin version**
Latest

**Plugin source**
- Github releases download

**Describe the bug**
The File group view triggers a fatal error when : 
- the Files Tools folder support have been enabled (plugin settings)
- the File tool is enabled in group
- the Default order is set to Date
Adding the following required clauses in the beginning of lib/functions.php fixes the issue:
```
use Elgg\Database\Select;
use Elgg\Database\QueryBuilder;
use Elgg\Database\Clauses\OrderByClause;
```

**To Reproduce**
1. Go to a new group
2. Enable File tool and save
3. Edit group and save Default File tools settings
4. Go to Group files
5. See error (fatal error : missing OrderByClause)

**Comment by jeabakker** [comment]
thanks for reporting, fixed it
